Record greg2
jstnzl/MarkThat pull request #6
Opened 2018-11-01 04:14 UTC by greghan9

Changed page titles to specific ones. Added back button to Record page

2018-11-01 23:40 UTC, jstnzl requested changes
Back button doesnt actually work, it just loads the previous page on top.
steps to repo- go to record, use software back button, hit hardware back button
I guess it's fine if we dont have back button for now so if you cant figure it out let me know we'll find something else to do

2018-11-01 23:40 UTC, jstnzl commented on app/src/main/java/com/example/justi/markthat/Record.java
> +       // setTitle(recordTitle);
Remove the comments if they dont work or arent needed

2018-11-01 23:40 UTC, jstnzl commented on app/src/main/java/com/example/justi/markthat/ViewRecording.java
> +        setTitle("MarkThat - View Recording(s)");
Change home to MarkThat - Home to be consistent

2018-11-05 00:39 UTC, greghan9 commented
Deleted lines for back button and changed title of home page

2018-11-05 00:43 UTC, merged